# Generated by Django 6.0.1 on 2026-01-10 18:27

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('total_seasons', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество сезонов')),
                ('total_episodes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Всего эпизодов')),
                ('average_episode_duration', models.IntegerField(default=45, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Средняя длительность эпизода (мин)')),
                ('genres', models.CharField(blank=True, max_length=255, verbose_name='Жанры')),
                ('poster_url', models.URLField(blank=True, null=True, verbose_name='URL постера')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='TMDB ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер сезона')),
                ('episode_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер эпизода')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название эпизода')),
                ('duration', models.IntegerField(default=45, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность (мин)')),
                ('air_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='planner.series', verbose_name='Сериал')),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
                'ordering': ['series', 'season_number', 'episode_number'],
                'unique_together': {('series', 'season_number', 'episode_number')},
            },
        ),
        migrations.CreateModel(
            name='WatchingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('duration_watched', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минут просмотрено')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_records', to='planner.episode', verbose_name='Эпизод')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='planner.series', verbose_name='Сериал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись просмотра',
                'verbose_name_plural': 'История просмотра',
                'ordering': ['-watched_at'],
            },
        ),
        migrations.CreateModel(
            name='UserViewingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_hours_available', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(24.0)], verbose_name='Часов в день')),
                ('last_season_watched', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Последний просмотренный сезон')),
                ('last_episode_watched', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Последний просмотренный эпизод')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Дата начала')),
                ('estimated_completion_date', models.DateField(blank=True, null=True, verbose_name='Планируемая дата завершения')),
                ('status', models.CharField(choices=[('watching', 'Смотрю'), ('completed', 'Завершено'), ('paused', 'На паузе'), ('planning', 'В планах')], default='watching', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='planner.series', verbose_name='Сериал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_plans', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'План просмотра',
                'verbose_name_plural': 'Планы просмотра',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'series')},
            },
        ),
    ]
