# Generated by Django 6.0.1 on 2026-01-11 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchinghistory',
            name='episode',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_records', to='planner.episode', verbose_name='Эпизод'),
        ),
    ]
