# Generated by Django 6.0 on 2026-01-15 18:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_watchinghistory_episode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг TMDB'),
        ),
        migrations.AddField(
            model_name='series',
            name='release_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выхода'),
        ),
        migrations.AlterField(
            model_name='userviewingplan',
            name='status',
            field=models.CharField(choices=[('watching', 'Смотрю'), ('completed', 'Завершено'), ('paused', 'На паузе'), ('planning', 'В планах'), ('dropped', 'Брошено')], default='watching', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='UserSeriesRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка (1-10)')),
                ('review', models.TextField(blank=True, verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='planner.series', verbose_name='Сериал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка пользователя',
                'verbose_name_plural': 'Оценки пользователей',
                'unique_together': {('user', 'series')},
            },
        ),
    ]
