# Generated by Django 6.0 on 2026-01-16 12:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_series_rating_series_release_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userviewingplan',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='userviewingplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userviewingplan',
            name='estimated_completion_date',
        ),
        migrations.RemoveField(
            model_name='userviewingplan',
            name='start_date',
        ),
        migrations.AddField(
            model_name='userviewingplan',
            name='episodes_per_day',
            field=models.IntegerField(default=2, help_text='Сколько эпизодов смотрите в день'),
        ),
        migrations.AddField(
            model_name='userviewingplan',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 16, 12, 2, 7, 735857, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userviewingplan',
            name='daily_hours_available',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='userviewingplan',
            name='last_episode_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userviewingplan',
            name='last_season_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userviewingplan',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='planner.series'),
        ),
        migrations.AlterField(
            model_name='userviewingplan',
            name='status',
            field=models.CharField(choices=[('watching', 'Смотрю'), ('completed', 'Завершено'), ('paused', 'На паузе'), ('planning', 'В планах'), ('dropped', 'Брошено')], default='planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='userviewingplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userviewingplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
